---
- name: Cisco IOS
  hosts: 111_L4_switches
  connection: local
  gather_facts: false

  vars:
    date: "{{ lookup('pipe', 'date +%Y.%b.%d.%a.%H%M%S') }}"


  tasks:

  - name: ios backup
    ios_command:
      timeout: 60
      commands: show run
    register: output

  - name: show output
    copy: content="{{ output.stdout[0] }}" dest=/opt/ansible/backup/{{ inventory_hostname }}.show_run.{{ date }}.txt

