---
- name: Cisco IOS
  hosts: 111_L4_switches
  connection: local
  gather_facts: false

  tasks:

  - name: run show version
    ios_command:
      commands: "show version"
    register: config

  - name: "Save output to /opt/ansible/backup/"
    debug: "msg={{config}}"
