---
- name: Cisco IOS
  hosts: 111_sw
  connection: local
  gather_facts: false
  vars:
          date: "{{ lookup('pipe', 'date +%Y.%b.%d.%a') }}"

  tasks:

  - name: show run
    ios_command:
      timeout: 60
      commands:
        - 'show run'
        - 'show inventory'
    register: output    

  - name: save output     
    blockinfile:
      create: yes
      dest: "/opt/ansible/backup/telstra_getconfig.{{ date }}.txt"
      marker: "#{mark} BLOCK GROUP 1"
      block: |
        {{ output.stdout[0] }}
        {{ output.stdout[1] }}
